version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5433:5432
    env_file:
      asyncdrf/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: asyncdrf
      dockerfile: Dockerfile
    volumes:
      - ./asyncdrf/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - asyncdrf/.env
