# Generated by Django 3.1.2 on 2020-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('actual_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
